version: 2.1
orbs:
    path-filtering: circleci/path-filtering@0.0.1
workflows:
    generate-config:
        jobs:
            - path-filtering/filter:
                mapping: |
                    src/.* build-code true
                    doc/.* build-docs true
            - testing:
                  command: |
                      echo ${build-code}

