version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Donald-Lao/segnull/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  helloword:
    environment:
      COUNT: 1
    docker:
        - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: |
          # echo Hello, World!
          # echo $COUNT
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/python:3.10.2
    steps:
      - path-filtering/set-parameters
orbs:
  path-filtering: circleci/path-filtering@0.1.3
  node: circleci/node@5.0.2
workflows:
    example-workflow:
      jobs:
        - path-filtering/filter
        - example-job
        - helloword
